/* eslint-disable @typescript-eslint/no-explicit-any */
import { createClient } from 'npm:@insforge/sdk'

const BASE_URL = Deno.env.get('INSFORGE_BASE_URL') ?? ''
const OPENROUTER_API_KEY = Deno.env.get('OPENROUTER_API_KEY') ?? ''
const MODELS = ['minimax/minimax-m3:free', 'poolside/laguna-s-2.1:free', 'nvidia/nemotron-3.5-lightning:free']
const MAX_PROMPT_LENGTH = 4000
const MAX_HABITS = 10
const MAX_COMPLETION_TOKENS = 2600
const MODEL_TIMEOUT_MS = 15_000
const RATE_LIMIT = 5
const RATE_WINDOW_MS = 10 * 60 * 1000
const rateLimitBuckets = new Map<string, { count: number; windowStartedAt: number }>()
const ALLOWED_ORIGINS = new Set(['https://5zz5dxgt.insforge.site', 'https://karenda.insforge.site', 'http://localhost:5173', 'http://127.0.0.1:5173'])

class RequestError extends Error { constructor(readonly status: number, readonly errorCode: string, message: string) { super(message) } }
function bearer(request: Request): string | null { return request.headers.get('Authorization')?.match(/^Bearer\s+(.+)$/i)?.[1]?.trim() ?? null }
function cors(request: Request): HeadersInit { const origin = request.headers.get('Origin'); return { 'Access-Control-Allow-Headers': 'Authorization, Content-Type', 'Access-Control-Allow-Methods': 'POST, OPTIONS', ...(origin && ALLOWED_ORIGINS.has(origin) ? { 'Access-Control-Allow-Origin': origin } : {}), Vary: 'Origin' } }
function response(request: Request, body: Record<string, unknown> | null, status: number): Response { const headers = new Headers(cors(request)); headers.set('Content-Type', 'application/json; charset=utf-8'); return new Response(body && JSON.stringify(body), { status, headers }) }
function fail(request: Request, error: RequestError): Response { const result = response(request, { error_code: error.errorCode, message: error.message }, error.status); if (error.status === 429) result.headers.set('Retry-After', String(Math.ceil(RATE_WINDOW_MS / 1000))); return result }
async function authenticated(request: Request) {
  if (!BASE_URL) throw new RequestError(503, 'BACKEND_UNAVAILABLE', 'La preparación de hábitos no está disponible.')
  const token = bearer(request); if (!token) throw new RequestError(401, 'UNAUTHORIZED', 'La sesión web no es válida.')
  const client = createClient({ baseUrl: BASE_URL, accessToken: token }); const { data, error } = await client.auth.getCurrentUser()
  if (error || !data?.user?.id) throw new RequestError(401, 'UNAUTHORIZED', 'La sesión web no es válida.')
  return { client, ownerId: data.user.id }
}
function limit(ownerId: string) { const now = Date.now(); const current = rateLimitBuckets.get(ownerId); if (!current || now - current.windowStartedAt >= RATE_WINDOW_MS) { rateLimitBuckets.set(ownerId, { count: 1, windowStartedAt: now }); return } if (current.count >= RATE_LIMIT) throw new RequestError(429, 'RATE_LIMITED', 'Se alcanzó el límite temporal de IA. Espera unos minutos e inténtalo nuevamente.'); current.count += 1 }
async function body(request: Request) { try { const value = await request.json(); if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error(); return value as Record<string, unknown> } catch { throw new RequestError(400, 'INVALID_REQUEST', 'La solicitud no es válida.') } }
function text(value: unknown, max: number, fallback: string | null = null): string | null { return typeof value === 'string' ? value.trim().slice(0, max) || fallback : fallback }
function prompt(value: unknown): string { const result = text(value, MAX_PROMPT_LENGTH, null); if (!result) throw new RequestError(400, 'INVALID_REQUEST', 'Describe al menos un hábito.'); return result }
function date(value: unknown, fallback: string): string { const result = text(value, 10, fallback) ?? fallback; if (!/^\d{4}-\d{2}-\d{2}$/.test(result)) throw new RequestError(502, 'INVALID_MODEL_RESPONSE', 'La respuesta de la IA no se pudo validar.'); return result }
function json(value: string): unknown { const cleaned = value.trim().replace(/^```(?:json)?/i, '').replace(/```$/, '').trim(); try { return JSON.parse(cleaned) } catch { throw new RequestError(502, 'INVALID_MODEL_RESPONSE', 'La respuesta de la IA no se pudo validar.') } }
async function model(modelName: string, messages: Array<{ role: string; content: string }>): Promise<string | null> {
  if (!OPENROUTER_API_KEY) throw new RequestError(503, 'AI_UNAVAILABLE', 'La preparación de hábitos no está configurada.')
  const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), MODEL_TIMEOUT_MS)
  try { const result = await fetch('https://openrouter.ai/api/v1/chat/completions', { method: 'POST', headers: { Authorization: `Bearer ${OPENROUTER_API_KEY}`, 'Content-Type': 'application/json', 'HTTP-Referer': 'https://5zz5dxgt.insforge.site', 'X-Title': 'Karenda' }, body: JSON.stringify({ model: modelName, messages, temperature: 0.1, max_tokens: MAX_COMPLETION_TOKENS, ...(modelName === MODELS[0] ? { response_format: { type: 'json_object' } } : {}) }), signal: controller.signal }); if (!result.ok) return null; const payload = await result.json(); return typeof payload?.choices?.[0]?.message?.content === 'string' ? payload.choices[0].message.content : null } catch { return null } finally { clearTimeout(timer) }
}
function normalize(raw: unknown, subjects: Array<{ id: string }>, groups: Array<{ id: string }>, referenceDate: string): Record<string, unknown>[] {
  if (!Array.isArray(raw) || raw.length > MAX_HABITS) throw new RequestError(502, 'INVALID_MODEL_RESPONSE', 'La respuesta de la IA no se pudo validar.')
  const subjectIds = new Set(subjects.map((item) => item.id)); const groupIds = new Set(groups.map((item) => item.id))
  return raw.map((item) => { if (!item || typeof item !== 'object') throw new RequestError(502, 'INVALID_MODEL_RESPONSE', 'La respuesta de la IA no se pudo validar.'); const value = item as Record<string, any>; const flags = Array.isArray(value.review_flags) ? value.review_flags.filter((flag: unknown) => typeof flag === 'string').slice(0, 5) : []; const subjectId = typeof value.subject_id === 'string' && subjectIds.has(value.subject_id) ? value.subject_id : null; const groupId = typeof value.personal_group_id === 'string' && groupIds.has(value.personal_group_id) ? value.personal_group_id : null; if (value.subject_id && !subjectId) flags.push('unknown_subject'); if (value.personal_group_id && !groupId) flags.push('unknown_personal_group'); const schedule = value.schedule ?? {}; return { name: text(value.name, 160, null) ?? 'Hábito sin nombre', description: text(value.description, 2000), color: null, subject_id: subjectId, personal_group_id: groupId, tracking_type: ['boolean', 'count', 'duration'].includes(value.tracking_type) ? value.tracking_type : 'boolean', unit: text(value.unit, 80), goal_value: typeof value.goal_value === 'number' && Number.isFinite(value.goal_value) ? Math.max(0, value.goal_value) : 1, evaluation_mode: value.evaluation_mode === 'period_quota' ? 'period_quota' : 'scheduled_occurrence', quota_period: ['day', 'week', 'month'].includes(value.quota_period) ? value.quota_period : null, miss_policy: value.miss_policy === 'keep_pending' ? 'keep_pending' : 'mark_missed', schedule: { unit: ['day', 'week', 'month'].includes(schedule.unit) ? schedule.unit : 'day', interval: typeof schedule.interval === 'number' ? Math.max(1, Math.floor(schedule.interval)) : 1, weekdays: Array.isArray(schedule.weekdays) ? schedule.weekdays.filter((day: unknown) => Number.isInteger(day) && Number(day) >= 1 && Number(day) <= 7) : [], dayOfMonth: Number.isInteger(schedule.dayOfMonth) ? schedule.dayOfMonth : null, anchorDate: schedule.anchorDate ? date(schedule.anchorDate, referenceDate) : null }, start_date: date(value.start_date, referenceDate), end_date: value.end_date ? date(value.end_date, referenceDate) : null, lifecycle_status: 'active', stats_enabled: true, note_policy: 'none', calendar_enabled: false, calendar_schedule: null, review_flags: [...new Set(flags)] } })
}
async function create(request: Request, input: Record<string, unknown>): Promise<Response> { const { client, ownerId } = await authenticated(request); limit(ownerId); const userPrompt = prompt(input.prompt); const referenceDate = date(input.reference_date, new Date().toISOString().slice(0, 10)); const subjectsResult = await client.database.from('subjects').select('id, name, code, abbreviation').order('name', { ascending: true }).limit(500); const groupsResult = await client.database.from('personal_groups').select('id, name').order('name', { ascending: true }).limit(500); if (subjectsResult.error || groupsResult.error) throw new RequestError(503, 'BACKEND_UNAVAILABLE', 'No se pudo cargar tu catálogo para preparar los hábitos.'); const catalog = { subjects: subjectsResult.data ?? [], personal_groups: groupsResult.data ?? [] }; const messages = [{ role: 'system', content: 'Eres un asistente de hábitos. Devuelve únicamente JSON válido con una propiedad habits, un arreglo de máximo 10 objetos. Usa exactamente los campos snake_case del contrato. No inventes UUID: usa solo los del catálogo. Las fechas son YYYY-MM-DD. Para leer 20 páginas usa tracking_type count, unit páginas, goal_value 20. schedule usa camelCase.' }, { role: 'user', content: JSON.stringify({ reference_date: referenceDate, time_zone: text(input.time_zone, 80, 'UTC'), catalog, user_text: userPrompt }) }]; for (const modelName of MODELS) { const content = await model(modelName, messages); if (!content) continue; try { const parsed = json(content) as Record<string, unknown>; return response(request, { habits: normalize(parsed.habits, catalog.subjects as Array<{ id: string }>, catalog.personal_groups as Array<{ id: string }>, referenceDate) }, 200) } catch (error) { if (!(error instanceof RequestError) || error.status !== 502) throw error } } throw new RequestError(503, 'AI_UNAVAILABLE', 'No se pudieron preparar los hábitos. Inténtalo nuevamente.') }
export default async function handle(request: Request): Promise<Response> { try { if (request.method === 'OPTIONS') return response(request, null, 204); if (request.method !== 'POST') return fail(request, new RequestError(405, 'METHOD_NOT_ALLOWED', 'El método solicitado no está disponible.')); return await create(request, await body(request)) } catch (error) { return fail(request, error instanceof RequestError ? error : new RequestError(503, 'BACKEND_UNAVAILABLE', 'La preparación de hábitos no está disponible.')) } }
