/* eslint-disable @typescript-eslint/no-explicit-any -- Integration function payloads and PostgREST projections are generated by existing Karenda edge contracts. */
import { aiEventDraftResponseSchema, eventInputSchema, entityIdSchema } from "../../src/services/validation.ts";
import { habitInputSchema, habitLocalDateSchema } from "../../src/services/habitValidation.ts";
import { DomainOperationError, type KarendaClient } from "./domain.ts";
import type { McpPrincipal } from "./oauth.ts";

type Row = Record<string, any>;

function getDatabase(client: KarendaClient): any {
  return client.database as any;
}

function parseOrThrow<T>(schema: { safeParse(value: unknown): { success: boolean; data?: T; error?: { issues?: Array<{ message?: string }> } } }, value: unknown): T {
  const result = schema.safeParse(value);
  if (!result.success) {
    throw new DomainOperationError("invalid_argument", result.error?.issues?.[0]?.message ?? "Los datos no son válidos.");
  }
  return result.data as T;
}

async function invokeFunction<T>(client: KarendaClient, slug: string, input: { method?: string; body?: unknown } = {}): Promise<T> {
  const { data, error } = await client.functions.invoke(slug, input as never);
  if (error) {
    const errorRecord = error as unknown as Record<string, unknown>;
    const status = Number(errorRecord.status ?? errorRecord.statusCode);
    if (status === 429) throw new DomainOperationError("unavailable", "Se alcanzó el límite temporal. Espera unos minutos y vuelve a intentarlo.");
    if (status === 403) throw new DomainOperationError("invalid_argument", "Esta función todavía no está habilitada para esta cuenta piloto.");
    throw new DomainOperationError("unavailable", "No se pudo completar la operación con la integración conectada.");
  }
  return data as T;
}

export async function getCanvasConnection(client: KarendaClient): Promise<unknown> {
  const result = await invokeFunction<{ connection: Record<string, unknown> | null }>(client, "karenda-canvas-connection", { method: "GET" });
  return result.connection;
}

export async function synchronizeCanvas(client: KarendaClient): Promise<unknown> {
  return await invokeFunction(client, "karenda-canvas-sync", { method: "POST", body: {} });
}

export async function listCanvasCourseLinks(client: KarendaClient, principal: McpPrincipal): Promise<Row[]> {
  const { data, error } = await getDatabase(client).from("canvas_course_links")
    .select("id, canvas_course_id, subject_id, canvas_name, canvas_code, canvas_term_name")
    .eq("owner_id", principal.ownerId).eq("active", true)
    .order("canvas_name", { ascending: true }).limit(500);
  if (error) throw new DomainOperationError("unavailable", "No se pudieron cargar las asignaturas vinculadas.");
  return (data ?? []).map((row: Row) => ({
    id: row.id, canvasCourseId: row.canvas_course_id, subjectId: row.subject_id,
    canvasName: row.canvas_name, canvasCode: row.canvas_code, canvasTermName: row.canvas_term_name,
  }));
}

export async function unlinkCanvasCourse(client: KarendaClient, linkId: string): Promise<void> {
  parseOrThrow(entityIdSchema, linkId);
  const { error } = await getDatabase(client).rpc("unlink_canvas_course_link", { p_course_link_id: linkId });
  if (error) throw new DomainOperationError("conflict", "No se pudo desvincular el curso. Revisa las relaciones y vuelve a intentarlo.");
}

export async function listCanvasReviews(client: KarendaClient, principal: McpPrincipal): Promise<Row[]> {
  const { data, error } = await getDatabase(client).from("canvas_review_items")
    .select("id, course_link_id, canvas_course_id, canvas_item_type, canvas_item_id, review_kind, title, source_url, source_excerpt, academic_activity_type, proposed_data, candidate_event_ids, created_at")
    .eq("owner_id", principal.ownerId).eq("status", "pending")
    .order("created_at", { ascending: true }).limit(500);
  if (error) throw new DomainOperationError("unavailable", "No se pudo cargar la bandeja de revisión de Canvas.");
  return (data ?? []).map((row: Row) => ({
    id: row.id, courseLinkId: row.course_link_id, canvasCourseId: row.canvas_course_id,
    canvasItemType: row.canvas_item_type, canvasItemId: row.canvas_item_id,
    reviewKind: row.review_kind, title: row.title, sourceUrl: row.source_url,
    sourceExcerpt: row.source_excerpt, academicActivityType: row.academic_activity_type,
    proposedData: row.proposed_data ?? {}, candidateEventIds: row.candidate_event_ids ?? [],
    createdAt: row.created_at,
  }));
}

export async function listCanvasSyncRuns(client: KarendaClient, principal: McpPrincipal): Promise<Row[]> {
  const { data, error } = await getDatabase(client).from("canvas_sync_runs")
    .select("id, trigger_type, status, counts, error_message, started_at, finished_at")
    .eq("owner_id", principal.ownerId).order("started_at", { ascending: false }).limit(10);
  if (error) throw new DomainOperationError("unavailable", "No se pudo cargar el historial de sincronización.");
  return (data ?? []).map((row: Row) => ({
    id: row.id, triggerType: row.trigger_type, status: row.status,
    counts: row.counts ?? {}, errorMessage: row.error_message,
    startedAt: row.started_at, finishedAt: row.finished_at,
  }));
}

export async function applyCanvasReview(client: KarendaClient, input: { reviewItemId: string; decision: string; eventId?: string; overrides?: Record<string, unknown> }): Promise<unknown> {
  return await invokeFunction(client, "karenda-canvas-review", {
    method: "POST",
    body: {
      reviewItemId: input.reviewItemId,
      decision: input.decision,
      eventId: input.eventId,
      overrides: input.overrides ?? {},
    },
  });
}

function validateTimeZone(value?: string): string {
  const timeZone = value?.trim() || "UTC";
  if (timeZone.length > 64) throw new DomainOperationError("invalid_argument", "La zona horaria no es válida.");
  try {
    new Intl.DateTimeFormat("es", { timeZone }).format();
  } catch {
    throw new DomainOperationError("invalid_argument", "La zona horaria no es válida.");
  }
  return timeZone;
}

function defaultReferenceDate(timeZone: string): string {
  const dateParts = new Intl.DateTimeFormat("en-CA", { timeZone, year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(new Date());
  const values = Object.fromEntries(dateParts.map((part) => [part.type, part.value]));
  return `${values.year}-${values.month}-${values.day}`;
}

function mapAnswers(answers?: Array<{ questionId: string; optionId?: string; otherText?: string; noPreference?: boolean }>): Row[] | undefined {
  if (!answers) return undefined;
  if (answers.length > 5) throw new DomainOperationError("invalid_argument", "La respuesta incluye demasiadas aclaraciones.");
  return answers.map((answer) => ({
    question_id: answer.questionId,
    option_id: answer.optionId ?? null,
    other_text: answer.otherText ?? null,
    no_preference: answer.noPreference === true,
  }));
}

export async function prepareAiEventDraft(client: KarendaClient, input: {
  prompt: string;
  mode: "quick" | "guided";
  timeZone?: string;
  referenceDate?: string;
  answers?: Array<{ questionId: string; optionId?: string; otherText?: string; noPreference?: boolean }>;
}): Promise<unknown> {
  const prompt = input.prompt.trim();
  if (!prompt || prompt.length > 4000) throw new DomainOperationError("invalid_argument", "Describe al menos un evento en un máximo de 4000 caracteres.");
  const timeZone = validateTimeZone(input.timeZone);
  const referenceDate = parseOrThrow(habitLocalDateSchema, input.referenceDate?.trim() || defaultReferenceDate(timeZone));
  const response = await invokeFunction<Row>(client, "karenda-ai-event-drafts", {
    method: "POST",
    body: { prompt, mode: input.mode, time_zone: timeZone, reference_date: referenceDate, answers: mapAnswers(input.answers) },
  });

  if (input.mode === "guided" && !input.answers?.length && Array.isArray(response.questions)) {
    if (response.questions.length > 5) throw new DomainOperationError("unavailable", "La IA devolvió demasiadas preguntas. Vuelve a intentarlo.");
    return { kind: "questions", questions: response.questions };
  }
  const parsed = parseOrThrow(aiEventDraftResponseSchema, { events: response.events });
  const subjectIds = [...new Set(parsed.events.map((event) => event.subject_id).filter((id): id is string => Boolean(id)))];
  const groupIds = [...new Set(parsed.events.map((event) => event.personal_group_id).filter((id): id is string => Boolean(id)))];
  if (subjectIds.length) {
    const { data, error } = await getDatabase(client).from("subjects").select("id").in("id", subjectIds);
    if (error || (data ?? []).length !== subjectIds.length) throw new DomainOperationError("unavailable", "La IA propuso una asignatura que ya no está disponible. Vuelve a generar el borrador.");
  }
  if (groupIds.length) {
    const { data, error } = await getDatabase(client).from("personal_groups").select("id").in("id", groupIds);
    if (error || (data ?? []).length !== groupIds.length) throw new DomainOperationError("unavailable", "La IA propuso un grupo que ya no está disponible. Vuelve a generar el borrador.");
  }
  return {
    kind: "drafts",
    events: parsed.events.map((event, index) => ({
      draftId: `ai-draft-${index + 1}`,
      input: {
        description: event.description,
        endAt: event.end_at,
        isAllDay: event.is_all_day,
        kind: event.kind,
        location: event.location,
        personalGroupId: event.personal_group_id,
        startAt: event.start_at,
        status: event.status,
        subjectId: event.subject_id,
        title: event.title,
      },
      newSubjectName: event.new_subject_name,
      newPersonalGroupName: event.new_personal_group_name,
      reviewFlags: event.review_flags,
    })),
  };
}

export async function prepareAiHabitDraft(client: KarendaClient, input: {
  prompt: string;
  mode: "quick" | "guided";
  timeZone?: string;
  referenceDate?: string;
  answers?: Array<{ questionId: string; optionId?: string; otherText?: string; noPreference?: boolean }>;
}): Promise<unknown> {
  const prompt = input.prompt.trim();
  if (!prompt || prompt.length > 4000) throw new DomainOperationError("invalid_argument", "Describe al menos un hábito en un máximo de 4000 caracteres.");
  const timeZone = validateTimeZone(input.timeZone);
  const referenceDate = parseOrThrow(habitLocalDateSchema, input.referenceDate?.trim() || defaultReferenceDate(timeZone));
  const response = await invokeFunction<Row>(client, "karenda-ai-habit-drafts", {
    method: "POST",
    body: { prompt, mode: input.mode, time_zone: timeZone, reference_date: referenceDate, answers: mapAnswers(input.answers) },
  });

  if (input.mode === "guided" && !input.answers?.length && Array.isArray(response.questions)) {
    if (response.questions.length > 5) throw new DomainOperationError("unavailable", "La IA devolvió demasiadas preguntas. Vuelve a intentarlo.");
    return { kind: "questions", questions: response.questions };
  }
  if (!Array.isArray(response.habits) || response.habits.length > 10) throw new DomainOperationError("unavailable", "La IA no devolvió borradores de hábitos válidos.");
  const drafts = response.habits.map((item: Row, index: number) => {
    const inputData = {
      calendarEnabled: item.calendar_enabled,
      calendarSchedule: item.calendar_schedule,
      color: item.color,
      description: item.description,
      endDate: item.end_date,
      evaluationMode: item.evaluation_mode,
      goalValue: item.goal_value,
      lifecycleStatus: item.lifecycle_status,
      missPolicy: item.miss_policy,
      name: item.name,
      notePolicy: item.note_policy,
      personalGroupId: item.personal_group_id,
      quotaPeriod: item.quota_period,
      schedule: item.schedule,
      startDate: item.start_date,
      statsEnabled: item.stats_enabled,
      subjectId: item.subject_id,
      trackingType: item.tracking_type,
      unit: item.unit,
    };
    const validatedInput = parseOrThrow(habitInputSchema, inputData);
    return { draftId: `ai-habit-draft-${index + 1}`, input: validatedInput, reviewFlags: Array.isArray(item.review_flags) ? item.review_flags : [] };
  });
  return { kind: "drafts", habits: drafts };
}

export async function saveAiEventDraft(client: KarendaClient, principal: McpPrincipal, input: { event: Record<string, unknown>; confirm: true }): Promise<unknown> {
  const parsed = parseOrThrow(eventInputSchema, input.event);
  const ownerId = principal.ownerId;
  if (parsed.subjectId) {
    const { data, error } = await getDatabase(client).from("subjects").select("id").eq("owner_id", ownerId).eq("id", parsed.subjectId).maybeSingle();
    if (error || !data) throw new DomainOperationError("invalid_argument", "La asignatura indicada no pertenece a esta cuenta.");
  }
  if (parsed.personalGroupId) {
    const { data, error } = await getDatabase(client).from("personal_groups").select("id").eq("owner_id", ownerId).eq("id", parsed.personalGroupId).maybeSingle();
    if (error || !data) throw new DomainOperationError("invalid_argument", "El grupo indicado no pertenece a esta cuenta.");
  }
  const payload = {
    owner_id: ownerId, kind: parsed.kind, title: parsed.title,
    subject_id: parsed.subjectId ?? null, personal_group_id: parsed.personalGroupId ?? null,
    start_at: parsed.isAllDay ? `${parsed.startAt.slice(0, 10)}T00:00:00.000Z` : new Date(parsed.startAt).toISOString(),
    end_at: parsed.endAt ? parsed.isAllDay ? `${parsed.endAt.slice(0, 10)}T00:00:00.000Z` : new Date(parsed.endAt).toISOString() : null,
    is_all_day: parsed.isAllDay, status: parsed.status, location: parsed.location ?? null,
    description: parsed.description ?? null,
  };
  const { data, error } = await getDatabase(client).from("events").insert([payload])
    .select("id, kind, title, subject_id, personal_group_id, start_at, end_at, is_all_day, status, location, description, created_at, updated_at").single();
  if (error || !data) throw new DomainOperationError("unavailable", "No se pudo guardar el borrador como evento.");
  return data;
}

export async function saveAiHabitDraft(client: KarendaClient, principal: McpPrincipal, input: { habit: Record<string, unknown>; confirm: true }): Promise<unknown> {
  const parsed = parseOrThrow(habitInputSchema, input.habit);
  for (const [table, id] of [["subjects", parsed.subjectId], ["personal_groups", parsed.personalGroupId]] as const) {
    if (!id) continue;
    const { data, error } = await getDatabase(client).from(table).select("id").eq("owner_id", principal.ownerId).eq("id", id).maybeSingle();
    if (error || !data) throw new DomainOperationError("invalid_argument", "La relación indicada no pertenece a esta cuenta.");
  }
  const payload = {
    owner_id: principal.ownerId, name: parsed.name, description: parsed.description, color: parsed.color,
    subject_id: parsed.subjectId, personal_group_id: parsed.personalGroupId,
    tracking_type: parsed.trackingType, unit: parsed.unit, goal_value: parsed.goalValue,
    evaluation_mode: parsed.evaluationMode, quota_period: parsed.quotaPeriod,
    miss_policy: parsed.missPolicy, schedule: parsed.schedule, start_date: parsed.startDate,
    end_date: parsed.endDate, lifecycle_status: parsed.lifecycleStatus, stats_enabled: parsed.statsEnabled,
    note_policy: parsed.notePolicy, calendar_enabled: parsed.calendarEnabled,
    calendar_schedule: parsed.calendarSchedule,
  };
  const { data, error } = await getDatabase(client).from("habits").insert([payload])
    .select("id, name, description, color, subject_id, personal_group_id, tracking_type, unit, goal_value, evaluation_mode, quota_period, miss_policy, schedule, start_date, end_date, lifecycle_status, stats_enabled, note_policy, calendar_enabled, calendar_schedule, created_at, updated_at").single();
  if (error || !data) throw new DomainOperationError("unavailable", "No se pudo guardar el borrador como hábito.");
  const version = await getDatabase(client).from("habit_schedule_versions").insert([{
    owner_id: principal.ownerId, habit_id: data.id, schedule: parsed.schedule,
    evaluation_mode: parsed.evaluationMode, goal_value: parsed.goalValue,
    quota_period: parsed.quotaPeriod, miss_policy: parsed.missPolicy,
    effective_from: parsed.startDate,
  }]);
  if (version.error) {
    await getDatabase(client).from("habits").delete().eq("owner_id", principal.ownerId).eq("id", data.id);
    throw new DomainOperationError("unavailable", "No se pudo guardar la regla inicial del hábito.");
  }
  return data;
}
